### ISSUE TITLE
Getting stuck on Create New Function level

### ISSUE THREAD

**Issue by sleepdoctors** [JWWeatherman/math_bot#57] opened 2018-06-03 23:00 UTC
In the "create new function" level between move right level and move left level, I am having the same difficulty on both 1366x768 and 1920x1080 resolutions.  The first part says click + and drag u-turn next to person.  The u turn icon is in the black box and you can't drag it out of the box down into the tray next to the person, it only drags out of the box down into the tray next to the rocket.  I then cannot add any icons to the black box.  I can't find any combination of icons that works.  One time I got the rocket to fire and hit the portal but it told me to try again anyhow.  I hope some of this is making sense.  I hope this helps sort out the bugs for your slower future programmers.  haha.  Ken

![mathbot create new function](https://user-images.githubusercontent.com/39888841/40892135-54498896-6760-11e8-8c3b-42c3223647e7.jpg)

**Comment by JWWeatherman** [comment] 2018-06-03 23:18
I think this is a combination of bugs. The first is that the UI is messed up based on the screenshot.

The second is that I think the instructions are unclear. I’ll try to get some video tutorials figured out ASAP.

**Comment by JWWeatherman** [comment] 2018-06-15 22:44
Hey @sleepdoctors can you take a look at the help video and let me know if it makes it more clear:

https://twitter.com/MathBot_dotcom/status/1007696248529477633

These will be inside the app on each level soon, but for now they are numbered. I think you are on Planet 1, Level 4 or 5.

**Comment by JWWeatherman** [comment] 2018-08-21 16:27
I think this a duplicate of #5

**Closed by JWWeatherman** 2018-08-21 16:27 UTC
